# Generated by Django 3.0.1 on 2020-01-02 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AylienUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Url to analysis of Aylien')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Date of url analysis with Aylien')),
                ('user', models.ForeignKey(blank=True, help_text='User to send analysis', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AylienSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='Aylien text summary analysis')),
                ('sentences', models.TextField(blank=True, help_text='Aylien sentences summary analysis')),
                ('url', models.ForeignKey(blank=True, help_text='Url to analysis', on_delete=django.db.models.deletion.CASCADE, to='aylien.AylienUrl')),
            ],
        ),
        migrations.CreateModel(
            name='AylienSentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polarity', models.CharField(blank=True, help_text='Aylien polarity sentiment analysis', max_length=200)),
                ('subjectivity', models.CharField(blank=True, help_text='Aylien subjectivity sentiment analysis', max_length=200)),
                ('text', models.TextField(blank=True, help_text='Aylien subjectivity sentiment analysis')),
                ('polarity_confidence', models.DecimalField(decimal_places=2, help_text='Aylien polarityconfidence sentiment analysis', max_digits=10)),
                ('subjectivity_confidence', models.DecimalField(decimal_places=2, help_text='Aylien subjectivityconfidence sentiment analysis', max_digits=10)),
                ('url', models.ForeignKey(blank=True, help_text='Url to analysis', on_delete=django.db.models.deletion.CASCADE, to='aylien.AylienUrl')),
            ],
        ),
        migrations.CreateModel(
            name='AylienEntities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, help_text='Aylien language entities analysis', max_length=200)),
                ('text', models.TextField(blank=True, help_text='Aylien text entities analysis')),
                ('entities', models.TextField(blank=True, help_text='Aylien entities analysis')),
                ('url', models.ForeignKey(blank=True, help_text='Url to analysis', on_delete=django.db.models.deletion.CASCADE, to='aylien.AylienUrl')),
            ],
        ),
        migrations.CreateModel(
            name='AylienConcepts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, help_text='Aylien language concepts analysis', max_length=200)),
                ('text', models.TextField(blank=True, help_text='Aylien text concepts analysis')),
                ('concepts', models.TextField(blank=True, help_text='Aylien concepts analysis')),
                ('url', models.ForeignKey(blank=True, help_text='Url to analysis', on_delete=django.db.models.deletion.CASCADE, to='aylien.AylienUrl')),
            ],
        ),
        migrations.CreateModel(
            name='AylienClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, help_text='Aylien language classify analysis', max_length=200)),
                ('text', models.TextField(blank=True, help_text='Aylien text classify analysis')),
                ('categories', models.TextField(blank=True, help_text='Aylien categories classify analysis')),
                ('url', models.ForeignKey(blank=True, help_text='Url to analysis', on_delete=django.db.models.deletion.CASCADE, to='aylien.AylienUrl')),
            ],
        ),
    ]
