# Generated by Django 3.0.1 on 2020-01-02 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aylien', '0002_auto_20200102_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aylienclassify',
            name='url',
            field=models.ForeignKey(blank=True, help_text='Url to analysis', on_delete=django.db.models.deletion.CASCADE, related_name='classify', to='aylien.AylienUrl'),
        ),
        migrations.AlterField(
            model_name='aylienconcepts',
            name='url',
            field=models.ForeignKey(blank=True, help_text='Url to analysis', on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='aylien.AylienUrl'),
        ),
        migrations.AlterField(
            model_name='aylienentities',
            name='url',
            field=models.ForeignKey(blank=True, help_text='Url to analysis', on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='aylien.AylienUrl'),
        ),
        migrations.AlterField(
            model_name='ayliensentiment',
            name='url',
            field=models.ForeignKey(blank=True, help_text='Url to analysis', on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='aylien.AylienUrl'),
        ),
        migrations.AlterField(
            model_name='ayliensummary',
            name='url',
            field=models.ForeignKey(blank=True, help_text='Url to analysis', on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='aylien.AylienUrl'),
        ),
    ]
